# Site settings
title: Derek Thor Cary
email: derekthorcary@gmail.com
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://derekthorcary.github.io" # the base hostname & protocol for your site
github_username:  derekthorcary

# Build settings
markdown: kramdown
